### PR TITLE
updated to qwik release candidate

### PR DESCRIPTION
**Pull request by tzdesign**
Since this morning qwik is on the release candidate with a very stable version.

Please merge this as soon as possible.

### CODE REVIEW

**Comment by tzdesign** [comment]
Did you created a new release as well? We would really appreciate, as we are using your package in our app.

Thanks and have a great weekend.

**Comment by egmaleta** [comment]
I am glad you are using my humble icon library port, and happy it is working for you, I'll check if there are new icons and release a brand new version for you folks.

**Comment by egmaleta** [comment]
here you have
https://github.com/egmaleta/qwik-feather-icons/releases/tag/v1.2.1

**Comment by tzdesign** [comment]
Thank you very much 🙏

**Pull request merged**
